services:
  db-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_DIALECT=mssql
      - DB_HOST=host.docker.internal
      - DB_PORT=14340
      - DB_NAME=your_database_name
      - DB_USER=sa
      - DB_PASSWORD=your_strong_password
      - ODBC_DRIVER=ODBC Driver 18 for SQL Server